---
# 这个剧本在所有节点上运行
 
- name: 关闭swap
  lineinfile:
    dest: /etc/fstab
    regexp: ".*swap"
    line: ""

- name: 即时生效
  shell: setenforce 0 ; swapoff -a

- name: 拷贝时区
  copy: src=/usr/share/zoneinfo/America/Los_Angeles dest=/etc/localtime

- name: 添加hosts
  template: src=hosts.j2 dest=/etc/hosts 


